# Generated by Django 5.2.8 on 2026-09-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='include_weekends',
            field=models.BooleanField(default=False),
        ),
    ]
